### ISSUE TITLE
Not authorised message after sending private message

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#566]
<img width="465" alt="screen shot 2016-04-24 at 13 53 19" src="https://cloud.githubusercontent.com/assets/11997264/14767701/635f0860-0a24-11e6-9f27-e74ac480a42d.png">

Now I don't know if it was sent.

**Comment by mvl22** [comment]
What web address is that screenshot from?

**Comment by roxannedebeaux** [comment]
I've gone back into my list of messages. I can click on the other messages
and read them, however when I try to click on this particular message I get
the same screen. The URL is http://camcycle.cyclescape.org/threads/2520 (I
don't know if this is the same as the original screen shot).

Can you advise if the other person was sent the message? It's quite urgent.


Kind Regards,

Roxanne De Beaux
Cycling Campaign Officer

*Cambridge Cycling Campaign*
Charity, no. 1138090

w: http://www.camcycle.org.uk/     e: roxanne.debeaux@camcycle.org.uk
Join the Campaign at: http://www.camcycle.org.uk/membership/join/
*Donate to support the work we do. Text "CYCC11 £5" to 70070*

**Comment by nikolai-b** [comment]
Hi,
Sorry about this.  I think I've made the rules a bit too tight on this.  I've got a fix but wanted to check it and the message in question was made just before we took a back up so it'll have to wait till tomorrow.

Is that soon enough?

**Comment by roxannedebeaux** [comment]
No, I need to know now. I'll see if I can find another way to contact.

On Monday, 25 April 2016, Nikolai <notifications@github.com> wrote:

> Hi,
> Sorry about this. I think I've made the rules a bit too tight on this.
> I've got a fix but wanted to check it and the message in question was made
> just before we took a back up so it'll have to wait till tomorrow.
>
> Is that soon enough?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclestreets/cyclescape/issues/566#issuecomment-214064983>
>


-- 
Kind Regards,

Roxanne De Beaux
Cycling Campaign Officer

*Cambridge Cycling Campaign*
Charity, no. 1138090

w: http://www.camcycle.org.uk/     e: roxanne.debeaux@camcycle.org.uk
Join the Campaign at: http://www.camcycle.org.uk/membership/join/
*Donate to support the work we do. Text "CYCC11 £5" to 70070*

**Comment by nikolai-b** [comment]
This should be fixed now, when I checked today the message was in the backup so I could check what was happening.  Thanks for the report.

**Comment by roxannedebeaux** [comment]
I still can't see the message and i still don't know if it sent. The same
error message is appearing.

Kind Regards,

Roxanne De Beaux
Cycling Campaign Officer

*Cambridge Cycling Campaign*
Charity, no. 1138090

w: http://www.camcycle.org.uk/     e: roxanne.debeaux@camcycle.org.uk
Join the Campaign at: http://www.camcycle.org.uk/membership/join/
*Donate to support the work we do. Text "CYCC11 £5" to 70070*

**Comment by nikolai-b** [comment]
Are you sure? I have just deployed so it might be a caching thing but you should be able to see `/threads/2520` now.  Can you try refreshing the page or on another device?

**Comment by roxannedebeaux** [comment]
I now have this situation (3 messages) and they are all showing non authorised when clicked. 

Also, I *really* need to have a notification when I get new messages. 

<img width="552" alt="screen shot 2016-04-26 at 19 03 24" src="https://cloud.githubusercontent.com/assets/11997264/14829128/dc28f3aa-0be1-11e6-84b2-d1875cd2c22c.png">

**Comment by nikolai-b** [comment]
Is this fixed now?

**Comment by nikolai-b** [comment]
@roxannedebeaux is this fixed now?
